name: univ_go
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter_dotenv: ^5.2.1
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  marquee: ^2.3.0
  shared_preferences: ^2.3.4
  smooth_page_indicator: ^1.2.0+3
  get: ^4.6.6
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  image_picker: ^1.0.4
  cached_network_image: ^3.4.1
  lottie: ^3.2.0
  shimmer: ^3.0.0
  timezone: ^0.10.0

dev_dependencies:
  test: ^1.25.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  fonts:
   - family:  UnivGoIcon
     fonts:
      - asset: fonts/UnivGoIcon.ttf
  assets:
    - assets/images/campus_placeholder.jpg
    - assets/images/campus_placeholder_circle1.png
    - assets/images/campus_placeholder_circle2.png
    - assets/images/campus_placeholder_dimmed.jpg
    - assets/images/news_placeholder.jpg
    - assets/animations/loading.json
    - assets/animations/success.json
    - assets/images/iisma.png
    - assets/images/iisma_detail.png
    - assets/images/polines1.jpg
    - assets/images/polines2.jpg
    - assets/images/polines3.jpg
    - assets/images/polines4.jpg
    - assets/images/logo.png
    - assets/images/logo_polines.png
    - assets/images/logo_undip.png
    - assets/images/logo_polkesmar.png
    - assets/images/logo_unnes.png
    - .env
