name: univ_go
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter_dotenv: ^5.2.1
  flutter:
    sdk: flutter
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  marquee: ^2.3.0
  shared_preferences: ^2.3.4
  smooth_page_indicator: ^1.2.0+3
  get: ^4.6.6
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  image_picker: ^1.0.4
  cached_network_image: ^3.4.1
  lottie: ^3.2.0
  shimmer: ^3.0.0
  timezone: ^0.10.0
  font_awesome_flutter: ^10.8.0
  fl_chart: ^0.69.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0

dev_dependencies:
  test: ^1.25.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true
  fonts:
   - family:  UnivGoIcon
     fonts:
      - asset: fonts/UnivGoIcon.ttf
  assets:
    - assets/animations/
    - assets/images/
    - .env
