/// Flutter icons UnivGoIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UnivGoIcon
///      fonts:
///       - asset: fonts/UnivGoIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class UnivGoIcon {
  UnivGoIcon._();

  static const _kFontFam = 'UnivGoIcon';
  static const String? _kFontPkg = null;

  static const IconData home = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeoutline = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
